# Generated by Django 5.2.6 on 2025-10-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('kicker', models.CharField(blank=True, max_length=255, verbose_name='Малый текст')),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('cta_link', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('video', models.FileField(upload_to='hero_videos/', verbose_name='Видео')),
                ('poster', models.ImageField(blank=True, upload_to='hero_posters/', verbose_name='Постер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Подпись под кружком')),
                ('cover_image', models.ImageField(upload_to='story_covers/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10)),
                ('file', models.FileField(upload_to='stories/')),
                ('poster', models.ImageField(blank=True, upload_to='stories_posters/')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мс)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_page.story')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
