# Generated by Django 5.2.8 on 2026-02-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0002_dessouser_birth_date_dessouser_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
