# Generated by Django 5.2.6 on 2025-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('youtube_url', models.URLField(help_text='https://www.youtube.com/watch?v=VIDEO_ID', verbose_name='YouTube URL')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='video_posters/', verbose_name='Постер (миниатюра)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'YouTube видео',
                'verbose_name_plural': 'YouTube видео',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='target_blank',
            field=models.BooleanField(default=True, verbose_name='Открывать в новой вкладке'),
        ),
    ]
