# Generated by Django 5.2.6 on 2025-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0002_youtubevideo_banner_target_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={},
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='embed_src',
            field=models.CharField(blank=True, max_length=500, verbose_name='Embed SRC из YouTube'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video_posters/'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Обычная ссылка YouTube'),
        ),
    ]
