# Generated by Django 5.2.6 on 2025-11-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0003_alter_youtubevideo_options_youtubevideo_embed_src_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка при клике'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='target_blank',
            field=models.BooleanField(default=False, verbose_name='Открывать в новом окне'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст поверх баннера'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='embed_src',
            field=models.CharField(blank=True, help_text='Например: https://www.youtube.com/embed/ID?si=XYZ', max_length=500, verbose_name='Embed SRC из YouTube (только src=...)'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='video_posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
