# Generated by Django 5.2.6 on 2025-11-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0004_alter_banner_options_alter_youtubevideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitem',
            name='cta_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для CTA'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='cta_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки (CTA)'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='poll_options',
            field=models.JSONField(blank=True, help_text='JSON массива строк, например: ["Да","Нет","Не знаю"]', null=True, verbose_name='Опции опроса'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='poll_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вопрос опроса'),
        ),
    ]
