# Generated by Django 5.2.6 on 2025-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0005_storyitem_cta_link_storyitem_cta_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyitem',
            name='poll_options',
        ),
        migrations.RemoveField(
            model_name='storyitem',
            name='poll_question',
        ),
        migrations.AddField(
            model_name='storyitem',
            name='cta_enabled',
            field=models.BooleanField(default=False, verbose_name='Показывать CTA'),
        ),
        migrations.AlterField(
            model_name='storyitem',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
