# Generated by Django 5.2.6 on 2026-01-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0006_remove_storyitem_poll_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='storyitem',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='poster',
        ),
    ]
