# Generated by Django 5.2.8 on 2026-03-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0007_productstrawberrychoco'),
        ('orders', '0004_order_is_paid_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='strawberry_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='flowers_catalog_page.productstrawberrychoco'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='strawberry_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='flowers_catalog_page.productstrawberrychoco'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='strawberry_products',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='flowers_catalog_page.productstrawberrychoco'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers_catalog_page.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers_catalog_page.product'),
        ),
    ]
