# Generated by Django 5.2.8 on 2026-03-27 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0007_productstrawberrychoco'),
        ('orders', '0005_cartitem_strawberry_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='strawberry_product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flowers_catalog_page.product'),
            preserve_default=False,
        ),
    ]
