# Generated by Django 5.2.8 on 2026-03-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0007_productstrawberrychoco'),
        ('orders', '0006_remove_orderitem_strawberry_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='strawberry_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='flowers_catalog_page.productstrawberrychoco'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flowers_catalog_page.product'),
        ),
    ]
