# Generated by Django 5.2.6 on 2025-11-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL-адрес'),
        ),
    ]
