# Generated by Django 5.2.6 on 2025-11-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0002_alter_collection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание (линия под названием)'),
        ),
    ]
