# Generated by Django 5.2.6 on 2025-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0003_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlideProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('kicker', models.CharField(blank=True, max_length=255, verbose_name='Малый текст')),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('cta_link', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('video', models.FileField(upload_to='hero_videos/', verbose_name='Видео')),
                ('poster', models.ImageField(blank=True, upload_to='hero_posters/', verbose_name='Постер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
