# Generated by Django 5.2.6 on 2026-01-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0004_heroslideproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение')], default='image', max_length=10, verbose_name='Тип медиа'),
        ),
    ]
