# Generated by Django 5.2.8 on 2026-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0005_alter_product_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа'),
        ),
    ]
