# Generated by Django 5.2.8 on 2026-02-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers_catalog_page', '0006_alter_product_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStrawberryChoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание (линия под названием)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('media_type', models.CharField(choices=[('image', 'Изображение')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(upload_to='products/strawberries/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Всего продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Клубника в шоколаде',
                'verbose_name_plural': 'Клубника в шоколаде',
                'ordering': ['order'],
            },
        ),
    ]
